name: Build and Store Artifacts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            arch: aarch64
            toolchain: stable
          - target: x86_64-unknown-linux-gnu
            arch: amd64
            toolchain: stable

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        if [ "${{ matrix.arch }}" = "aarch64" ]; then
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libsdl2-dev:arm64 libsdl2-image-dev:arm64
        else
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev
        fi

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}

    - name: Install cross
      run: cargo install cross

    - name: Build
      run: cross build --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}/debug/*
